image: archlinux
packages:
  - rustup
sources:
  - https://git.sr.ht/~robotmay/amdgpu-fancontrol
environment:
  RUST_TEST_THREADS: 1
tasks:
  - setup: |
      rustup toolchain install nightly stable
      cd amdgpu-fancontrol/
      rustup run stable cargo fetch
  - stable: |
      rustup default stable
      cd amdgpu-fancontrol/
      cargo build --verbose
      cargo test --verbose
  - nightly: |
      rustup default nightly
      cd amdgpu-fancontrol/
      cargo build --verbose ||:
      cargo test --verbose  ||:
  - docs: |
      cd amdgpu-fancontrol/
      rustup run stable cargo doc --no-deps
      rustup run nightly cargo doc --no-deps ||:
